{
 "title": "Horizontal Pod Autoscaling Example",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Cluster Auto Scaling", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Nodes by Instance Type",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "count(kubelet_node_name) by (beta_kubernetes_io_instance_type)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Pod Auto Scaling", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "hpa-example php-apache service requests-per-second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "rate(traefik_service_requests_total{service=\"hpa-example-php-apache-80@kubernetes\",code=\"200\"}[2m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Pods",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "count(kube_pod_info{namespace=\"hpa-example\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}