apiVersion: v1
kind: Pod
metadata:
  name: pod
spec:
  #nodeSelector:
    #node.kubernetes.io/instance-type: "g5.8xlarge"
  containers:
  - name: pod
    image: iankoulski/do-nvtop
    command: ["/bin/sh"]
    args: ["-c", "while true; do date; sleep 10; done"]
    resources:
      limits:
        nvidia.com/gpu: 1
        vpc.amazonaws.com/efa: 1
      requests:
        nvidia.com/gpu: 1
        vpc.amazonaws.com/efa: 1

