apiVersion: v1
kind: Pod
metadata:
  name: pod
spec:
  #nodeSelector:
    #node.kubernetes.io/instance-type: "m5.xlarge"
  containers:
  - name: pod
    image: iankoulski/do-curl
    command: ["/bin/sh"]
    args: ["-c", "while true; do date; sleep 10; done"]
    securityContext:
      privileged: true
      runAsNonRoot: false
      runAsUser: 0
