apiVersion: v1
kind: Pod
metadata:
  name: gpu-burn
spec:
  restartPolicy: OnFailure
  containers:
  - name: gpu-burn-test
    image: iankoulski/gpuburn:latest
    command: ["/bin/sh"]
    args: ["-c", "/opt/gpuburn/gpu_burn 120"]
    resources:
      limits:
        nvidia.com/gpu: 4
