#FROM pytorch/pytorch:2.0.1-cuda11.7-cudnn8-runtime

FROM nvcr.io/nvidia/pytorch:23.08-py3

ENV DEBIAN_FRONTEND=noninteractive

RUN apt update && apt install -y git vim curl htop

RUN pip3 install python-etcd

RUN mkdir -p /workspace/

WORKDIR /workspace

#RUN git clone https://github.com/lessw2020/fsdp_llm.git
RUN git clone https://github.com/kanwaljitkhurmi/fsdp_llm_copy.git

RUN pip install -U --index-url https://aiinfra.pkgs.visualstudio.com/PublicPackages/_packaging/Triton-Nightly/pypi/simple/ triton-nightly

WORKDIR /workspace/fsdp_llm_copy

#RUN sed -i config/nanogpt_config.py -e 's/str = "1B"/str = "10.5M"/g'
#RUN sed -i config/nanogpt_config.py -e 's/iters_to_run: int = 8 /iters_to_run: int = 800 /g'

