apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nvtop
spec:
  selector:
    matchLabels:
      name: nvtop
  template:
    metadata:
      labels:
        name: nvtop
    spec:
      containers:
        - name: nvtop
          image: iankoulski/do-nvtop:latest
          command: ["/bin/bash"]
          args: ["-c", "while true; do date; sleep 10; done"]
