apiVersion: batch/v1
kind: Job
metadata:
  name: job
spec:
  template:
    spec:
      #nodeSelector:
      #  kubernetes.io/hostname: "${node_name}"
      containers:
      - name: job
        image: ubuntu:22.04
        command: ["bash", "-c",  "hostname; ls -alh /"]
      restartPolicy: Never
  backoffLimit: 2
