apiVersion: v1
kind: Pod
metadata:
  name: pod
spec:
  #nodeSelector:
  #  kubernetes.io/hostname: "${NODE_NAME}"
  containers:
  - name: pod
    image: ${REGISTRY}${IMAGE}${TAG}
    command: ["/bin/sh"]
    args: ["-c", "while true; do date; sleep 10; done"]
