apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ${APP_NAME}
  namespace: ${NAMESPACE}
  labels:
    app: ${APP_NAME}
spec:
  selector:
    matchLabels:
      name: ${APP_NAME}
  template:
    metadata:
      labels:
        name: ${APP_NAME}
    spec:
      affinity:
        nodeAffinity:
          # EFA supported instances: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/efa.html#efa-instance-types
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: "node.kubernetes.io/instance-type"
                    operator: In
                    values:
                      - c5n.18xlarge
                      - c5n.metal
                      - g4dn.metal
                      - c5n.9xlarge
                      - i3en.24xlarge
                      - i3en.metal
                      - inf1.24xlarge
                      - m5dn.24xlarge
                      - m5n.24xlarge
                      - p3dn.24xlarge
                      - r5dn.24xlarge
                      - r5n.24xlarge
                      - p4d.24xlarge
                      - hpc6a.48xlarge
                      - dl1.24xlarge
                      - g5.48xlarge
                      - g5.8xlarge
                      - ml.g5.8xlarge
                      - p4de.24xlarge
                      - trn1.32xlarge
                      - trn1n.32xlarge
                      - p5.48xlarge
                      - p5e.48xlarge
                      - p5en.48xlarge
      containers:
      - name: ${APP_NAME}
        image: ${REGISTRY}${IMAGE}${TAG}
        command: ["/bin/bash"]
        args: ["-c", "while true; do echo ''; date; sleep 3; done"]
        securityContext:
          privileged: true
        volumeMounts:
        - name: efa-vol
          mountPath: "/dev/infiniband"
        - name: class-vol
          mountPath: "/sys/class/infiniband"
        - name: devices-vol
          mountPath: "/sys/devices"
      volumes:
      - name: efa-vol
        hostPath:
          path: "/dev/infiniband"
      - name: class-vol
        hostPath:
          path: "/sys/class/infiniband"
      - name: devices-vol
        hostPath:
          path: "/sys/devices"
