apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: do-eks-yaml-p5-cbr
  version: "1.32"
  region: us-west-2
  tags:
    karpenter.sh/discovery: do-eks-yaml-p5-cbr

availabilityZones:
  - us-west-2a
  - us-west-2b
  - us-west-2c

managedNodeGroups:

  - name: sys
    instanceType: c5.2xlarge
    desiredCapacity: 1
    iam:
      withAddonPolicies:
        autoScaler: true
        cloudWatch: true
 
nodeGroups: 
  - name: p5-cbr
    instanceType: p5.48xlarge
    instancePrefix: p5-cbr
    privateNetworking: true
    availabilityZones: ["us-west-2c"]
    efaEnabled: true
    minSize: 0
    desiredCapacity: 1
    maxSize: 8
    volumeSize: 500
    capacityReservation:
      capacityReservationTarget:
        capacityReservationID: "cr-xxxxxxxxxxxxxx"
    instanceMarketOptions:
      marketType: "capacity-block"
    iam:
      withAddonPolicies:
        cloudWatch: true
        ebs: true
        fsx: true

iam:
  withOIDC: true
