apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: do-eks-sa-smhp-runai
  version: "1.31"
  region: us-west-2

availabilityZones:
  - us-west-2a
  - us-west-2b
  - us-west-2c

iam:
  withOIDC: true

managedNodeGroups:
  - name: runai-sys
    instanceType: m5.16xlarge
    instancePrefix: m5-16xl
    privateNetworking: true
    availabilityZones: ["us-west-2a"]
    labels: {"runai-system": "true", "role": "runai-system"}
    minSize: 0
    desiredCapacity: 2
    maxSize: 10
    volumeSize: 500
    iam:
      withAddonPolicies:
        fsx: true
        efs: true
        ebs: true
