apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: do-eks-yaml
  version: "1.28"
  region: us-east-1
  tags:
    karpenter.sh/discovery: do-eks-yaml

availabilityZones:
  - us-east-1a
  - us-east-1b
  - us-east-1c
  - us-east-1d

managedNodeGroups:

  - name: sys
    instanceType: m5.2xlarge
    desiredCapacity: 1
    iam:
      withAddonPolicies:
        cloudWatch: true
 
  - name: g4dn
    instanceType: g4dn.8xlarge
    instancePrefix: g4dn
    privateNetworking: true
    availabilityZones: ["us-east-1a","us-east-1b","us-east-1c","us-east-1d"]
    efaEnabled: false
    minSize: 0
    desiredCapacity: 0
    maxSize: 10
    volumeSize: 50
    iam:
      withAddonPolicies:
        cloudWatch: true
        ebs: true
        efs: true
        fsx: true

iam:
  withOIDC: true
