apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: do-eks-yaml
  version: "1.25"
  region: us-west-2
  tags:
    karpenter.sh/discovery: do-eks-yaml

availabilityZones:
  - us-west-2a
  - us-west-2b
  - us-west-2c
  - us-west-2d

managedNodeGroups:

  - name: sys
    instanceType: m5.2xlarge
    desiredCapacity: 1
    iam:
      withAddonPolicies:
        cloudWatch: true
 
  - name: g4dn
    instanceType: g4dn.8xlarge
    instancePrefix: g4dn
    privateNetworking: true
    availabilityZones: ["us-west-2a","us-west-2b","us-west-2c","us-west-2d"]
    efaEnabled: false
    minSize: 0
    desiredCapacity: 0
    maxSize: 10
    volumeSize: 50
    iam:
      withAddonPolicies:
        cloudWatch: true
        ebs: true
        efs: true
        fsx: true

iam:
  withOIDC: true
