apiVersion: v1
kind: Pod
metadata:
  name: fsx-app
spec:
  containers:
  - name: app
    image: centos
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo \"hello from FSx\" >> /data/out.txt; sleep 5; done"]
    volumeMounts:
    - name: fsx-pv
      mountPath: /data
  volumes:
  - name: fsx-pv
    persistentVolumeClaim:
      claimName: fsx-pvc
